# Generated by Django 5.2.15 on 2026-07-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_siteconfig_delete_carouselslide_delete_galleryimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the image', max_length=255)),
                ('image', models.ImageField(help_text='Upload the image file here', upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Upload',
                'verbose_name_plural': 'Admin Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
