# Generated by Django 5.2.15 on 2026-07-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_adminupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUpload',
            new_name='Gallery',
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
    ]
