# Generated by Django 5.2.8 on 2025-11-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('tags', models.JSONField()),
                ('moreCount', models.IntegerField()),
                ('level', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('aiTools', models.CharField(max_length=50)),
                ('modules', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
                ('students', models.CharField(max_length=20)),
            ],
        ),
    ]
