# Generated by Django 5.2.8 on 2025-11-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='aiTools',
        ),
        migrations.RemoveField(
            model_name='course',
            name='moreCount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.AddField(
            model_name='course',
            name='gradient',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
