# Generated by Django 5.2.15 on 2026-08-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_topic_module_delete_module_delete_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, help_text='2-character course code for Student IDs (e.g., PY for Python, DS for Data Science, ME for MERN)', max_length=10),
        ),
    ]
