# Generated by Django 5.2.15 on 2026-08-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_event_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='List of event highlights/takeaways strings'),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.CharField(blank=True, help_text='Speaker or host name/title', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='time_range',
            field=models.CharField(blank=True, help_text='Custom display time e.g. 10:00 AM - 4:00 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
