# Generated by Django 5.2.15 on 2026-08-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_registration_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_form_schema',
            field=models.JSONField(blank=True, default=list, help_text="Custom Google Forms-like fields schema. List of objects e.g. [{'id': 'college_year', 'label': 'Year of Study', 'type': 'select', 'options': ['1st Year', '2nd Year', '3rd Year', '4th Year'], 'required': True}]"),
        ),
        migrations.AddField(
            model_name='registration',
            name='custom_answers',
            field=models.JSONField(blank=True, default=dict, help_text='Custom Google Forms-like responses submitted by the registrant'),
        ),
    ]
