# Generated by Django 5.2.15 on 2026-08-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_registration_form_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='form_branch_mode',
            field=models.CharField(choices=[('required', 'Required (Mandatory)'), ('optional', 'Optional (Non-Mandatory)'), ('hidden', 'Hidden (Do Not Show)')], default='hidden', max_length=15, verbose_name='Branch / Department Field'),
        ),
        migrations.AddField(
            model_name='event',
            name='form_college_mode',
            field=models.CharField(choices=[('required', 'Required (Mandatory)'), ('optional', 'Optional (Non-Mandatory)'), ('hidden', 'Hidden (Do Not Show)')], default='optional', max_length=15, verbose_name='College / Organization Field'),
        ),
        migrations.AddField(
            model_name='event',
            name='form_github_mode',
            field=models.CharField(choices=[('required', 'Required (Mandatory)'), ('optional', 'Optional (Non-Mandatory)'), ('hidden', 'Hidden (Do Not Show)')], default='hidden', max_length=15, verbose_name='GitHub / Portfolio Link Field'),
        ),
        migrations.AddField(
            model_name='event',
            name='form_phone_mode',
            field=models.CharField(choices=[('required', 'Required (Mandatory)'), ('optional', 'Optional (Non-Mandatory)'), ('hidden', 'Hidden (Do Not Show)')], default='required', max_length=15, verbose_name='Phone Number Field'),
        ),
        migrations.AddField(
            model_name='event',
            name='form_roll_no_mode',
            field=models.CharField(choices=[('required', 'Required (Mandatory)'), ('optional', 'Optional (Non-Mandatory)'), ('hidden', 'Hidden (Do Not Show)')], default='hidden', max_length=15, verbose_name='Student Roll No / USN Field'),
        ),
        migrations.AddField(
            model_name='event',
            name='form_year_mode',
            field=models.CharField(choices=[('required', 'Required (Mandatory)'), ('optional', 'Optional (Non-Mandatory)'), ('hidden', 'Hidden (Do Not Show)')], default='hidden', max_length=15, verbose_name='Year of Study Field'),
        ),
        migrations.AddField(
            model_name='registration',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='github_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_form_schema',
            field=models.JSONField(blank=True, default=list, help_text="Custom Google Forms-like fields schema. List of objects e.g. [{'id': 'tshirt', 'label': 'T-Shirt Size', 'type': 'select', 'options': ['S', 'M', 'L', 'XL'], 'required': True}]"),
        ),
    ]
