# Generated by Django 5.2.15 on 2026-08-12 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusCrewRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('registration_type', models.CharField(choices=[('student', 'Student'), ('college', 'College Inquiry')], db_index=True, max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('college_name', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('year_of_study', models.CharField(blank=True, max_length=50)),
                ('student_primary_interest', models.CharField(blank=True, choices=[('AI', 'AI & Machine Learning'), ('Web/App Development', 'Web/App Development'), ('Data', 'Data Science & Analytics'), ('Cybersecurity', 'Cybersecurity'), ('Cloud/DevOps', 'Cloud & DevOps'), ('Entrepreneurship/Innovation', 'Entrepreneurship & Innovation'), ('Other', 'Other')], max_length=100)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('official_email', models.EmailField(blank=True, max_length=150)),
                ('college_primary_interest', models.CharField(blank=True, choices=[('Campus Crew chapter', 'Campus Crew chapter'), ('Workshop or expert session', 'Workshop or expert session'), ('Student project program', 'Student project program'), ('Hackathon or innovation activity', 'Hackathon or innovation activity'), ('Discuss options', 'Discuss options')], max_length=100)),
                ('authority_confirmed', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('privacy_acknowledged', models.BooleanField(default=True)),
                ('whatsapp_opt_in', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(auto_now_add=True)),
                ('privacy_policy_version', models.CharField(default='2026.04', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_crew_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campus Crew Registration',
                'verbose_name_plural': 'Campus Crew Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
