# Generated by Django 5.2.15 on 2026-07-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0010_studentregistration_why_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
