# Generated by Django 5.2.15 on 2026-08-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0012_alter_studentregistration_status'),
        ('signin', '0013_resync_pk_sequences'),
    ]

    operations = [
    ]
