# Generated by Django 5.2.15 on 2026-08-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0014_merge_20260830_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='crue_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
